### ISSUE TITLE
Can't precompile on julia-0.5

### ISSUE THREAD

**Issue by davidavdav** [dancasimiro/WAV.jl#38]
Hi, 

I consistently get this error when loading WAV in julia-0.5-rc1:
```julia
using WAV
INFO: Precompiling module WAV...
ERROR: Failed to precompile WAV to /Users/david/.julia/lib/v0.5/WAV.ji
 in compilecache(::String) at ./loading.jl:505
 in require(::Symbol) at ./loading.jl:364
```
I can't tell whether it is a WAV or a julia-0.5 problem, other packages don't give pre-compilation errors, but is occurs only in julia-0.5. 

I've re-installed METADATA and WAV, but to no avail.

**Comment by dancasimiro** [comment]
This might be a Julia bug. I can reproduce the bug on julia-0.5-rc1. Strangely, I *cannot* reproduce the bug on julia-0.5-rc0 and julia-0.6-dev.166. I don't know what is happening. I will dig further.

**Comment by davidavdav** [comment]
OK, for me this bug disappeared on -rc2 as wel.
